import { describe, expect, it } from "vitest";
import { allocateExperimentVariant, buildPromotionPlan, canonicalizeAllocation, createAtomicProposalBackend, createAtomicProposalStore, issueAllocationReceipt, verifyAllocationReceipt } from "../src/lp-allocation.js";
const allocation = { experimentId: "hero-2026", experimentRevision: 4, variants: [{ id: "control", weight: 7000 }, { id: "new-hero", weight: 3000 }] };
const hash = "a".repeat(64);
describe("allocation", () => {
	it("canonicalizes order and keeps input unchanged", () => { const reversed = { ...allocation, variants: allocation.variants.toReversed() }; const before = JSON.stringify(reversed); expect(canonicalizeAllocation(allocation)).toBe(canonicalizeAllocation(reversed)); expect(JSON.stringify(reversed)).toBe(before); expect(allocateExperimentVariant(allocation, "opaque-subject-1")).toEqual({ variantId: "new-hero", bucket: 8570, experimentRevision: 4 }); expect(allocateExperimentVariant(allocation, "日本語😀").bucket).toBeGreaterThanOrEqual(0); });
	it("fails invalid weights and subject bounds closed", () => { expect(() => canonicalizeAllocation({ ...allocation, variants: [{ id: "a", weight: 1 }, { id: "b", weight: 1 }] })).toThrow(); expect(() => allocateExperimentVariant(allocation, "")).toThrow(); expect(() => allocateExperimentVariant(allocation, "x".repeat(257))).toThrow(); });
	it("signs, verifies, and rejects tampering", async () => { let signed = ""; const r = await issueAllocationReceipt(allocation, allocateExperimentVariant(allocation, "private"), { sign: async (p) => { signed = p; return "sig"; } }, "2026-08-25T00:00:00.000Z", 60); const verifier = { verify: async (p: string, s: string) => p === signed && s === "sig" }; expect(await verifyAllocationReceipt(allocation, r, verifier, "2026-08-25T00:00:30.000Z")).toBe(true); expect(await verifyAllocationReceipt(allocation, { ...r, bucket: 10000 }, verifier, "2026-08-25T00:00:30.000Z")).toBe(false); expect(await verifyAllocationReceipt(allocation, { ...r, expiresAt: r.issuedAt }, verifier, "2026-08-25T00:00:30.000Z")).toBe(false); });
	it("fails closed at expiry, future skew, unknown fields, empty signatures, and verifier exceptions", async () => { const r = await issueAllocationReceipt(allocation, { variantId: "control", bucket: 0, experimentRevision: 4 }, { sign: async () => "sig" }, "2026-08-25T00:00:00.000Z", 60); const throwing = { verify: async () => { throw new Error("bad"); } }; const accepting = { verify: async () => true }; expect(await verifyAllocationReceipt(allocation, r, throwing, "2026-08-25T00:01:00.000Z")).toBe(false); expect(await verifyAllocationReceipt(allocation, { ...r, signature: "" }, accepting, "2026-08-25T00:00:01.000Z")).toBe(false); expect(await verifyAllocationReceipt(allocation, { ...r, bucket: 7000 }, accepting, "2026-08-25T00:00:01.000Z")).toBe(false); expect(await verifyAllocationReceipt(allocation, { ...r, extra: true } as never, accepting, "2026-08-25T00:00:01.000Z")).toBe(false); expect(await verifyAllocationReceipt(allocation, { ...r, issuedAt: "2026-08-25T00:10:00.000Z" }, accepting, "2026-08-25T00:00:01.000Z")).toBe(false); });
});
const evidence = { sourceRevision: 9, evidenceRevision: 10, expectedEvidenceRevision: 10, evidenceId: "evidence-1", evidenceHash: hash, observedAt: "2026-08-24T00:00:00.000Z", samples: 1200, guardrails: [{ metricId: "error-rate", value: 0.01, maxRegression: 0.02 }] };
const approval = { actorType: "human" as const, approvalId: "approval-1", actorId: "alice", approvedAt: "2026-08-25T00:00:00.000Z", proposalId: "proposal-1", experimentId: "hero-2026", evidenceId: "evidence-1", evidenceHash: hash, selectedVariantId: "new-hero", proposalRevision: 2, experimentRevision: 9, sourceRevision: 9, evidenceRevision: 10 };
function input(overrides: Record<string, unknown> = {}) { return { proposalId: "proposal-1", proposalRevision: 2, proposalStatus: "approved" as const, experimentId: "hero-2026", experimentRevision: 9, experimentStatus: "running" as const, allocation: { ...allocation, experimentId: "hero-2026", experimentRevision: 9 }, selectedVariantId: "new-hero", allocationRevision: 9, sourceRevision: 9, evidence, minSamples: 1000, humanApproval: approval, verifyHuman: async () => true, now: "2026-08-25T00:00:00.000Z", changes: [{ repository: "org/site", path: "lp/hero.json", summary: "promote" }], ...overrides }; }
describe("promotion", () => { it("binds approval and evidence and returns only a plan", async () => { const plan = await buildPromotionPlan(input()); expect(plan.kind).toBe("git-change-plan"); expect(plan.receipt.planDigest).toHaveLength(64); }); it("rejects replay and missing verifier", async () => { await expect(buildPromotionPlan(input({ humanApproval: { ...approval, proposalId: "other" } }))).rejects.toThrow(); await expect(buildPromotionPlan(input({ verifyHuman: undefined }))).rejects.toThrow(); await expect(buildPromotionPlan(input({ evidence: { ...evidence, evidenceRevision: 9 } }))).rejects.toThrow(); }); });
it("rejects nested unknown fields, unsafe revisions, time order, and paths", async () => { await expect(buildPromotionPlan(input({ evidence: { ...evidence, extra: true } }))).rejects.toThrow(); await expect(buildPromotionPlan(input({ humanApproval: { ...approval, extra: true } }))).rejects.toThrow(); await expect(buildPromotionPlan(input({ evidence: { ...evidence, guardrails: [{ ...evidence.guardrails[0], extra: true }] } }))).rejects.toThrow(); await expect(buildPromotionPlan(input({ proposalRevision: 1.5 }))).rejects.toThrow(); await expect(buildPromotionPlan(input({ now: "2026-08-24T00:00:00.000Z" }))).rejects.toThrow(); await expect(buildPromotionPlan(input({ changes: [{ repository: "org/site", path: "lp/..\\secret\u007f", summary: "x" }] }))).rejects.toThrow(); });
describe("atomic backend", () => { it("uses separate handles over shared backend", async () => { const backend = createAtomicProposalBackend(); const a = createAtomicProposalStore(backend); const b = createAtomicProposalStore(backend); const x = { id: "p", revision: 0, digest: hash, payload: {} }; expect((await a.claim(x)).accepted).toBe(true); expect((await b.claim({ ...x, digest: "b".repeat(64) })).accepted).toBe(false); expect((await b.claim({ ...x, revision: 1, digest: "b".repeat(64) })).accepted).toBe(true); expect((await a.get("p"))?.revision).toBe(1); }); });

describe("failure and boundary matrix", () => {
	it("rejects comma keys, accessors, prototypes, cycles, bigint, and oversized payloads", async () => {
		const store = createAtomicProposalStore(); const base = { id: "p", revision: 0, digest: hash, payload: {} };
		await expect(store.claim({ ...base, id: "a,b" })).rejects.toThrow();
		const accessor = Object.defineProperty({ ...base }, "id", { get: () => "p", enumerable: true }); await expect(store.claim(accessor)).rejects.toThrow();
		await expect(store.claim(Object.assign(Object.create(null), base))).rejects.toThrow();
		const cycle: Record<string, unknown> = {}; cycle.self = cycle; await expect(store.claim({ ...base, payload: cycle })).rejects.toThrow();
		await expect(store.claim({ ...base, payload: { value: BigInt(1) } })).rejects.toThrow();
		await expect(store.claim({ ...base, payload: { value: "x".repeat(33_000) } })).rejects.toThrow();
		const nested: Record<string, unknown> = {}; Object.defineProperty(nested, "secret", { get: () => { throw new Error("must not run"); }, enumerable: true }); await expect(store.claim({ ...base, payload: { nested } })).rejects.toThrow();
	});
	it("handles backend corrupt reads and commit-before/after failures", async () => {
		const x = { id: "p", revision: 0, digest: hash, payload: {} };
		const before = { get: async () => undefined, claimCanonical: async () => { throw new Error("before"); } };
		await expect(createAtomicProposalStore(before).claim(x)).rejects.toThrow("before");
		let calls = 0; const after = { get: async () => x, claimCanonical: async () => { calls++; if (calls === 1) throw new Error("after"); return { accepted: true, canonical: x }; } };
		const retry = createAtomicProposalStore(after); await expect(retry.claim(x)).rejects.toThrow("after"); const recovered = await retry.claim(x); expect(recovered.accepted).toBe(true); expect(recovered.canonical).toEqual(x);
		const corrupt = { get: async () => ({ id: "p", revision: 0, digest: "bad", payload: {} }), claimCanonical: async () => ({ accepted: false, canonical: x }) };
		await expect(createAtomicProposalStore(corrupt).get("p")).rejects.toThrow("CORRUPT");
	});
	it("rejects stale and conflicting next revisions while converging identical retries", async () => {
		const backend = createAtomicProposalBackend(); const a = createAtomicProposalStore(backend); const b = createAtomicProposalStore(backend); const first = { id: "p", revision: 0, digest: hash, payload: {} }; await a.claim(first);
		const left = { ...first, revision: 1, digest: "b".repeat(64) }; const right = { ...first, revision: 1, digest: "c".repeat(64) }; const [l, r] = await Promise.all([a.claim(left), b.claim(right)]); expect(Number(l.accepted) + Number(r.accepted)).toBe(1); expect((await a.claim(left)).canonical.revision).toBe(1); expect((await b.claim({ ...first, revision: 0 })).accepted).toBe(false);
	});
	it("aligns two contexts at the atomic primitive before initial conflict", async () => {
		const target = createAtomicProposalBackend(); let arrivals = 0; let release!: () => void; const gate = new Promise<void>((resolve) => { release = resolve; });
		const gated = { get: target.get, claimCanonical: async (candidate: Parameters<typeof target.claimCanonical>[0]) => { arrivals++; if (arrivals === 2) release(); await gate; return target.claimCanonical(candidate); } };
		const a = createAtomicProposalStore(gated); const b = createAtomicProposalStore(gated); const x = { id: "race", revision: 0, digest: hash, payload: {} }; const y = { ...x, digest: "d".repeat(64) }; const [left, right] = await Promise.all([a.claim(x), b.claim(y)]); expect(Number(left.accepted) + Number(right.accepted)).toBe(1);
	});
	it("aligns next-revision conflicts and converges identical claims", async () => {
		const target = createAtomicProposalBackend(); const first = { id: "next", revision: 0, digest: hash, payload: {} }; const a0 = createAtomicProposalStore(target); await a0.claim(first); let arrivals = 0; let release!: () => void; const gate = new Promise<void>((resolve) => { release = resolve; }); const gated = { get: target.get, claimCanonical: async (candidate: Parameters<typeof target.claimCanonical>[0]) => { arrivals++; if (arrivals === 2) release(); await gate; return target.claimCanonical(candidate); } }; const a = createAtomicProposalStore(gated); const b = createAtomicProposalStore(gated); const left = { ...first, revision: 1, digest: "b".repeat(64) }; const right = { ...first, revision: 1, digest: "c".repeat(64) }; const [l, r] = await Promise.all([a.claim(left), b.claim(right)]); expect(Number(l.accepted) + Number(r.accepted)).toBe(1); release(); const same = await Promise.all([a.claim(left), b.claim(left)]); expect(same[0].accepted && same[1].accepted).toBe(true); expect(same[0].canonical).toEqual(same[1].canonical);
	});
});
